# Generated by Django 5.2.3 on 2025-08-17 16:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order_management.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='KhaltiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khalti_token', models.CharField(max_length=255)),
                ('khalti_payment_id', models.CharField(blank=True, max_length=100)),
                ('khalti_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('khalti_status', models.CharField(blank=True, max_length=50)),
                ('khalti_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_transaction', to='payment_gateway.payment')),
            ],
            options={
                'verbose_name': 'Khalti Transaction',
                'verbose_name_plural': 'Khalti Transactions',
            },
        ),
        migrations.CreateModel(
            name='EsewaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esewa_token', models.CharField(max_length=255)),
                ('esewa_payment_id', models.CharField(blank=True, max_length=100)),
                ('esewa_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esewa_status', models.CharField(blank=True, max_length=50)),
                ('esewa_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_transaction', to='payment_gateway.payment')),
            ],
            options={
                'verbose_name': 'eSewa Transaction',
                'verbose_name_plural': 'eSewa Transactions',
            },
        ),
    ]
