# Generated by Django 5.2.4 on 2025-09-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EsewaTransaction',
        ),
    ]
